services:
  backend:
    build: .
    ports:
      - "5002:5002"  # Varmista, että tässä käytetään oikeaa porttia
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - "69:80"  # Nginxin portti, varmista, että se on oikea
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: linuxkurssi
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: linuxkurssi
      MYSQL_DATABASE: exampledb
    ports:
      - "3307:3306"
